export const SDM = [
  {
    Nama: "Novita Hakim",
    Jabatan: "Komisaris Utama",
    kategori: "Komisaris",
    image: "https://i.ibb.co/L8K2nTL/1516939254771.jpg",
    profil: [
      "Alumni Master of  Business Administration - Loyola Marymount University",
      "Berpengalaman lebih dari 30 tahun di bidang perbankan",
      "Pernah menjabat sebagai Komisaris di PT Bank Harda Internasional",
    ],
  },
  {
    Nama: "Sandi Brata Simanjuntak",
    Jabatan: "Komisaris",
    kategori: "Komisaris",
    image: "https://i.ibb.co/pfmxycf/1651400185221.jpg",
    profil: [
      "Alumni Master of Science International Banking & Finance – Edinburgh Napier University",
      "Berpengalaman di bidang perbankan diantaranya pernah bekerja di Philippine National Bank , BNI-Hongkong Branch",
      "Pernah menjabat sebagai Division Head of Digital Banking and Information Technology di BPR Universal",
    ],
  },
  // {
  //   Nama: "Vacant",
  //   Jabatan: "Direktur Utama",
  //   kategori: "Direksi",
  //   image: "https://i.ibb.co/Sy3nJZV/person-1.jpg",
  // },
  {
    Nama: "Parsaoran Gultom",
    Jabatan: "Direktur Operasional",
    kategori: "Direksi",
    image: "https://i.ibb.co/Sy3nJZV/person-1.jpg",
    profil: [
      "Alumni Magister Manajemen – Universitas Diponegoro",
      "Berpengalaman lebih dari 30 tahun di bidang perbankan",
      "Direktur BPR Sembada",
    ],
  },
  {
    Nama: "Meilia Kosasih",
    Jabatan: "Ka.Bag Bisnis",
    kategori: "Kabag",
    image: "https://i.ibb.co/Sy3nJZV/person-1.jpg",
    profil: [
      "Alumni Manajemen – UKRIDA",
      "Berpengalaman lebih dari 20 tahun di bidang perbankan",
      "Pernah menjabat sebagai Kepala Cabang Bank Harda Internasional",
    ],
  },
  // {
  //   Nama: "Vacant",
  //   Jabatan: "Ka.Bag Operasional",
  //   kategori: ["Bag Bisnis", "Kabag"],
  //   image: "https://i.ibb.co/Sy3nJZV/person-1.jpg",
  // },
  // {
  //   Nama: "Melissa Mathilda Laurenzia P",
  //   Jabatan: "PE Manajemen Resiko. Kepatuhan & APU-PPT",
  //   kategori: "Kabag",
  //   image: "https://i.ibb.co/Sy3nJZV/person-1.jpg",
  // },
  {
    Nama: "Lie Se Mui",
    Jabatan: "PE Audit Intern",
    kategori: "Kabag",
    image: "https://i.ibb.co/Sy3nJZV/person-1.jpg",
    profil: ["None", "None", "None"],
  },
  // {
  //   Nama: "Helen Ang",
  //   Jabatan: "Account Officer",
  //   kategori: ["Bag Binis", "Staf"],
  //   image: "https://i.ibb.co/Sy3nJZV/person-1.jpg",
  //   profil: ["None", "None", "None"],
  // },
  // {
  //   Nama: "Ricky Permana",
  //   Jabatan: "Account Officer",
  //   kategori: ["Bag Bisnis", "Staf"],
  //   image: "https://i.ibb.co/Sy3nJZV/person-1.jpg",
  //   profil: ["None", "None", "None"],
  // },
  // {
  //   Nama: "Meilia Kosasih",
  //   Jabatan: "Funding Officer",
  //   kategori: ["Bag Bisnis", "Staf"],
  //   image: "https://i.ibb.co/Sy3nJZV/person-1.jpg",
  //   profil: ["None", "None", "None"],
  // },
  // {
  //   Nama: "Adek Fortulan Georgy S",
  //   Jabatan: "Legal",
  //   kategori: ["Bag Bisnis", "Staf"],
  //   image: "https://i.ibb.co/Sy3nJZV/person-1.jpg",
  // },
  // {
  //   Nama: "Vacant",
  //   Jabatan: "Collector/Remidial",
  //   kategori: ["Bag Bisnis", "Staf"],
  //   image: "https://i.ibb.co/Sy3nJZV/person-1.jpg",
  // },
  // {
  //   Nama: "Kristiana Romauli N",
  //   Jabatan: "Customer Service",
  //   kategori: ["Bag Operasional", "Staf"],
  //   image: "https://i.ibb.co/Sy3nJZV/person-1.jpg",
  // },
  // {
  //   Nama: "Kristiana Romauli N",
  //   Jabatan: "Teller",
  //   kategori: ["Bag Operasional", "Staf"],
  //   image: "https://i.ibb.co/Sy3nJZV/person-1.jpg",
  // },
  // {
  //   Nama: "Pesta Lasronita P",
  //   Jabatan: "Akunting",
  //   kategori: ["Bag Operasional", "Staf"],
  //   image: "https://i.ibb.co/Sy3nJZV/person-1.jpg",
  // },
  // {
  //   Nama: "Teguh Nugroho",
  //   Jabatan: "IT Support",
  //   kategori: ["Bag Operasional", "Staf"],
  //   image: "https://i.ibb.co/Sy3nJZV/person-1.jpg",
  // },
  // {
  //   Nama: "Jehan Sandy Cahya R",
  //   Jabatan: "IT Developer",
  //   kategori: ["Bag Operasional", "Staf"],
  //   image: "https://i.ibb.co/Sy3nJZV/person-1.jpg",
  // },
  // {
  //   Nama: "Liau Eddy",
  //   Jabatan: "HRD & GA",
  //   kategori: ["Bag Operasional", "Staf"],
  //   image: "https://i.ibb.co/Sy3nJZV/person-1.jpg",
  // },
  // {
  //   Nama: "Beni Wijaya",
  //   Jabatan: "Analis Kredit",
  //   kategori: ["Bag Operasional", "Staf"],
  //   image: "https://i.ibb.co/Sy3nJZV/person-1.jpg",
  // },
  // {
  //   Nama: "Jill Michel Wattimury",
  //   Jabatan: "Admin Kredit",
  //   kategori: ["Bag Operasional", "Staf"],
  //   image: "https://i.ibb.co/Sy3nJZV/person-1.jpg",
  // },
];
